[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "funclite2"
version = "0.1.0"
description = "A set of lightweight helper functions, mostly around base type manipulation and file system work."
readme = "README.md"
requires-python = ">=3.8"
license = { text = "MIT" }
authors = [
    { name = "gmonkman", email = "funclite2@mistymountains.biz" }
]

dependencies = [
    "fuckit~=4.8.1",
    "numpy~=2.5.3",
    "python-dateutil~=2.9.0.post0",
]


[tool.setuptools.packages.find]
where = ["."]
